version: "3.3"

services:
  database:
    image: mysql:8.0.35
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "banking"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "P@ssW0rd"
      MYSQL_ROOT_PASSWORD: "P@ssW0rd"
    ports:
      - "3306:3306"