spring:
  profiles:
    active: dev, prod
    default: dev
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: banking
  datasource:
    url: jdbc:mysql://localhost:3306/banking
    username: db_user
    password: P@ssW0rd
server:
  port: 8080
app:
  jwt-token: my-32-character-ultra-secure-and-ultra-long-secret
---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: banking
  datasource:
    url: ${DB_JDBC}
    username: ${DB_USER}
    password: ${DB_PASS}
server:
  port: 3000
app:
  jwt-token: my-32-character-ultra-secure-and-ultra-long-secret