spring:
  profiles: default
  application:
    name: banking
  datasource:
    url: jdbc:mysql://localhost:3306/banking
    username: db_user
    password: P@ssW0rd
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
---
spring:
  profiles: deploy
  application:
    name: banking
  datasource:
    url: ${DB_JDBC}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 3000