spring:
  profiles:
    default: dev
  application:
    name: banking
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
app:
  jwt-token: my-32-character-ultra-secure-and-ultra-long-secret
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/banking
    username: db_user
    password: P@ssW0rd
server:
  port: 8089
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_JDBC}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: false
server:
  port: 3000